### ISSUE TITLE
Smoking Monk Mega Sampler Price per Stick

### ISSUE THREAD

**Issue by bradxeno** [SteveMcGrath/bidhistory#1]
http://bidhistory.rcigars.chigeek.com/?full_search=Drew%20Estate%20Smoking%20Monk%20Mega-Sampler&site=cbid&category=sampler

Doesn't seem to be recongnizing that its a 25 stick sampler, shows total price as the price per stick.

**Comment by SteveMcGrath** [comment]
Thats actually intended, as a Sampler could be anything from multiple vitolas, cigars, and even have non-cigar things.  I decided that at the end of the day, it made more sense to consider all samplers a single "unit".  Further by default they are excluded from the trending so that they do not corrupt the trends or statistical analysis.  If you set the category=sampler either in the search or in the searchbox on the site, it will override this behavior however.
